# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "130e87e7316cbdcc7734e8d97904fc17"
name = "private-client-order-manager"
handle = "private-client-order-manager"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "gestion-du-checkout-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
